#!/bin/sh

## Ford
python simulator.py --adaptive-model-path trained_models/fordA/budget/model-SAMPLE_RNN-fordA-2020-09-20-17-39-21_model_best.pkl.gz trained_models/fordA/budget/model-SAMPLE_RNN-fordA-2020-09-20-17-49-32_model_best.pkl.gz --baseline-model-path trained_models/fordA/standard/model-RNN-fordA-2020-09-21-11-41-27_model_best.pkl.gz --phased-model-folder trained_models/fordA/phased --skip-model-folder trained_models/fordA/skip --dataset-folder data/fordA/folds_20 --budget-start 5.5 --budget-end 16.0 --budget-step 0.5 --noise-params controllers/noise_params/bt_gaussian.json --output-folder $1/fordA --power-system-type bluetooth --skip-plotting

## Pedestrian
python simulator.py --adaptive-model-path trained_models/melbourne_pedestrian/budget/model-SAMPLE_RNN-melbourne-pedestrian-2020-09-15-22-25-53_model_best.pkl.gz trained_models/melbourne_pedestrian/budget/model-SAMPLE_RNN-melbourne-pedestrian-2020-09-15-22-43-47_model_best.pkl.gz --baseline-model-path trained_models/melbourne_pedestrian/standard/model-RNN-melbourne-pedestrian-2020-08-28-17-19-37_model_best.pkl.gz --phased-model-folder trained_models/melbourne_pedestrian/phased/ --skip-model-folder trained_models/melbourne_pedestrian/skip/ --dataset-folder data/melbourne_pedestrian/folds_20 --budget-start 5.5 --budget-end 16.0 --budget-step 0.5 --noise-params controllers/noise_params/bt_gaussian.json --output-folder $1/melbourne_pedestrian --power-system-type bluetooth --skip-plotting

## Whale
python simulator.py --adaptive-model-path trained_models/whale/budget/model-SAMPLE_RNN-whale-2020-09-17-18-56-21_model_best.pkl.gz trained_models/whale/budget/model-SAMPLE_RNN-whale-2020-09-17-19-45-02_model_best.pkl.gz --baseline-model-path trained_models/whale/standard/model-RNN-whale-2020-09-01-21-13-33_model_best.pkl.gz --skip-model-folder trained_models/whale/skip/ --phased-model-folder trained_models/whale/phased/ --dataset-folder data/whale/folds_30 --budget-start 5.5 --budget-end 16.0 --budget-step 0.5 --noise-params controllers/noise_params/bt_gaussian.json --output-folder $1/whale --power-system-type bluetooth --skip-plotting

## Pen Digits
python simulator.py --adaptive-model-path trained_models/pen_digits/budget/model-SAMPLE_RNN-pen-digits-2020-09-16-17-11-25_model_best.pkl.gz trained_models/pen_digits/budget/model-SAMPLE_RNN-pen-digits-2020-09-16-17-50-15_model_best.pkl.gz --baseline-model-path trained_models/pen_digits/standard/model-RNN-pen-digits-2020-08-28-23-24-40_model_best.pkl.gz --phased-model-folder trained_models/pen_digits/phased/ --skip-model-folder trained_models/pen_digits/skip/ --dataset-folder data/pen_digits/folds_8 --budget-start 5.5 --budget-end 16.0 --budget-step 0.5 --noise-params controllers/noise_params/bt_gaussian.json --output-folder $1/pen_digits --power-system-type bluetooth --skip-plotting

## UCI HAR
python simulator.py --adaptive-model-path trained_models/uci_har/budget/model-SAMPLE_RNN-uci-har-2020-09-17-10-42-32_model_best.pkl.gz trained_models/uci_har/budget/model-SAMPLE_RNN-uci-har-2020-09-17-13-52-22_model_best.pkl.gz --baseline-model-path trained_models/uci_har/standard/model-RNN-uci-har-2020-09-05-12-30-20_model_best.pkl.gz --skip-model-folder trained_models/uci_har/skip/ --phased-model-folder trained_models/uci_har/phased/ --dataset-folder data/uci_har/folds_50 --budget-start 5.5 --budget-end 16.0 --budget-step 0.5 --noise-params controllers/noise_params/bt_gaussian.json --output-folder $1/uci_har --power-system-type bluetooth --skip-plotting

## EMG
python simulator.py --adaptive-model-path trained_models/emg/budget/model-SAMPLE_RNN-emg-2020-09-16-19-40-02_model_best.pkl.gz trained_models/emg/budget/model-SAMPLE_RNN-emg-2020-09-16-20-41-43_model_best.pkl.gz --baseline-model-path trained_models/emg/standard/model-RNN-emg-2020-09-03-20-00-34_model_best.pkl.gz --phased-model-folder trained_models/emg/phased --skip-model-folder trained_models/emg/skip --dataset-folder data/emg/folds_50 --budget-start 5.5 --budget-end 16.0 --budget-step 0.5 --noise-params controllers/noise_params/bt_gaussian.json --output-folder $1/emg --power-system-type bluetooth --skip-plotting

## Pavement
python simulator.py --adaptive-model-path trained_models/pavement/budget/model-SAMPLE_RNN-pavement-2020-09-16-22-12-38_model_best.pkl.gz trained_models/pavement/budget/model-SAMPLE_RNN-pavement-2020-09-16-23-52-21_model_best.pkl.gz --baseline-model-path trained_models/pavement/standard/model-RNN-pavement-2020-09-02-19-59-51_model_best.pkl.gz --skip-model-folder trained_models/pavement/skip/ --phased-model-folder trained_models/pavement/phased/ --dataset-folder data/pavement/folds_30 --budget-start 5.5 --budget-end 16.0 --budget-step 0.5 --noise-params controllers/noise_params/bt_gaussian.json --output-folder $1/pavement --power-system-type bluetooth --skip-plotting
